[2025-04-05T08:08:52.006623+00:00] console.CRITICAL: Error thrown while running command "contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 1698): An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' at /var/www/vhosts/handyservice4you.at/update.handyservice4you.at/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:118)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1698): SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' at /var/www/vhosts/handyservice4you.at/update.handyservice4you.at/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:24)\n[previous exception] [object] (PDOException(code: 1698): SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' at /var/www/vhosts/handyservice4you.at/update.handyservice4you.at/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:33)","command":"contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction","message":"An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'"} []
